# File: _config.yml  (Project 1 — make it behave like Project 2)

title: "Data-Backed Decision Making for YouTube Campaigns"
description: |
  This project site is a reimagined real-world business case I faced.
  Featured is a 1:1 practical walk-through of my thinking, trade-offs, and execution
  as I did in my professional setting—shared without the sensitive business details!
author: "Liad Mizrachi"

# MUST match repo name (case-sensitive)
baseurl: "/Data-Backed-Decision-Making-for-Youtube-Campaigns"
url: "https://findliad.github.io"

# Author card content used by index.md
author_title: "Senior Product Manager"
author_summary: "I’m an independent critical thinker pursuing projects that deepen my technical fluency and showcase product sense in real-world scenarios."
author_subtitle: "I’m an independent critical thinker pursuing projects that deepen my technical fluency and showcase product sense in real-world scenarios."
author_photo: "/Data-Backed-Decision-Making-for-Youtube-Campaigns/assets/images/liad-mizrachi.jpg"

author_links:
  - label: "Portfolio"
    url: "https://findliad.github.io/"
    icon: "🏠"
  - label: "Home Git"
    url: "https://github.com/FindLiad"
    icon: "📦"
  - label: "LinkedIn"
    url: "https://www.linkedin.com/in/liad-mizrachi/"
    icon: "🔗"
  - label: "Email Me"
    url: "mailto:Liad%20Mizrachi%20<FindLiad@gmail.com>"
    icon: "✉️"

# Hero / social preview assets
hero_preview:        "/Data-Backed-Decision-Making-for-Youtube-Campaigns/assets/images/finished-dashboard.png"
hero_screenshot_url: "/Data-Backed-Decision-Making-for-Youtube-Campaigns/assets/images/finished-dashboard.png"
og_image:            "/Data-Backed-Decision-Making-for-Youtube-Campaigns/assets/images/finished-dashboard.png"

# Optional comic-strip images for the Summary section (use if you have them)
cartoon_context: "/Data-Backed-Decision-Making-for-Youtube-Campaigns/assets/images/story-context.png"
cartoon_action:  "/Data-Backed-Decision-Making-for-Youtube-Campaigns/assets/images/story-action.png"
cartoon_result:  "/Data-Backed-Decision-Making-for-Youtube-Campaigns/assets/images/story-result.png"

# Hero buttons
live_dashboard_url: "https://public.tableau.com/app/profile/liad.mizrachi/viz/YoutubeVisualization_17550201203060/Dashboard1?publish=yes"
next_project_url: "https://findliad.github.io/Human-Resources-Data-Visualization-Dashboard/#site-top"

# Theme + plugins (same as Project 2)
remote_theme: "pages-themes/cayman@v0.2.0"
plugins:
  - jekyll-remote-theme

# Jekyll defaults
readme_index:
  enabled: false
titles_from_headings:
  enabled: false
show_downloads: false
